name: 'Nombda hook'
description: 'GitHub Action to trigger Nombda hook'
author: 'Benjamin Jorand <benjamin.jorand@gmail.com>'
branding:
  icon: 'hexagon'
  color: 'red'
inputs:
  token:
    description: 'Nombda token'
  url:
    description: 'Nombda server URL'
  hook:
    description: 'Hook to run'
  action:
    description: 'Action to run in hook'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TOKEN: ${{ inputs.token }}
    URL: ${{ inputs.url }}
    HOOK: ${{ inputs.hook }}
    ACTION: ${{ inputs.action }}
